title: Jackson Geller

description: > #
  <strong>I'm Jackson Geller,</strong> <br/> developer for the web.
        <br />
baseurl: ""
url: "https://jaxgeller.com"

email: jacksongeller@gmail.com
twitter_username: jaxgeller
github_username: jaxgeller

markdown: kramdown

gems:
  - jekyll-sitemap
